### ISSUE TITLE
[BUG] Changed files from Pull Request wrong

### ISSUE THREAD

**Issue by dmyers** [tj-actions/eslint-changed-files#117]
I noticed that the way the action is pulling in the files from Git to determine the changed files seems to be odd. In my case the head ref sha1 is different than the PR commit sha1.

Have you seen this before? Is this an easy fix?

Here is my action usage:

```yaml
name: Lint

on: pull_request

defaults:
  run:
    working-directory: ./resources/assets

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      
      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install modules
        run: npm install
        
      - uses: tj-actions/eslint-changed-files@v6.4
        with:
          token: ${{ github.token }}
          config_path: "resources/assets/.eslintrc.js"
          extensions: "js,vue"
          extra_args: "--fix"

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          status_options: '--untracked-files=no'
          add_options: '-u'
          skip_dirty_check: false
          skip_fetch: true
          disable_globbing: true
```
