### ISSUE TITLE
unable to get Reviewdog eslint comments on the PR 

### ISSUE THREAD

**Issue by shashank-saxena** [tj-actions/eslint-changed-files#1304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

I am using this config but unable to get review comments on PR by Reviewdog or am i missing something that is not highlighted in doc
```
     - name: Validate code
        if: always()
        uses: tj-actions/eslint-changed-files@v20
        with:
          path: "Functions/functions"
          config_path: ".eslintrc.js"
          ignore_path: ".eslintignore"
          file_extensions: |
            **/*.ts
            **/*.tsx
            *.js
```

### To Reproduce

See the bug description

### What OS are you seeing the problem on?

macos-11

### Expected behavior?

Should have updated the PR comments

### Anything else?

logs from actions

![image](https://github.com/tj-actions/eslint-changed-files/assets/4866539/e0ffb7f0-883c-45b7-a69f-f6591eabed82)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
