### ISSUE TITLE
[BUG] `skip_annotations: true` still posts annotations 

### ISSUE THREAD

**Issue by rtizzy** [tj-actions/eslint-changed-files#1458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

When setting skip_annotations to true, annotations are still posted into the PR

### To Reproduce

Try the following config for this action

```
      - name: ESLint changed files with Reviewdog
        uses: tj-actions/eslint-changed-files@v21
        with:
          reporter: github-pr-review
          skip_annotations: true
          filter_mode: file
          config_path: ".eslintrc.json"
          ignore_path: ".eslintignore"
          extra_args: "--rulesdir eslint-rules"
          fail_on_error: true
```

Create a file that fails linting

```
let not_a_number: string = 12
let not_a_string: number = "sup"
```

Create a PR and annotations are posted. 

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-22.04

### Expected behavior?

eslint runs and otherwise fails if relevant but does not post any annotations. 

### Relevant log output

```shell
N/A
```

### Has all relevant logs been included?

- [X] I've included all relevant logs

### Anything else?

![image](https://github.com/tj-actions/eslint-changed-files/assets/523926/80a2d5e0-baaf-4887-b0e0-96519da3939b)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
