### ISSUE TITLE
[BUG] fail_on_error: false still fails the job

### ISSUE THREAD

**Issue by jkasztur** [tj-actions/eslint-changed-files#2049]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Even when I specify `fail_on_error: false` the job still fails when there are some eslint errors. It should pass even with errors
![image](https://github.com/user-attachments/assets/1728c2c6-b46b-4a47-b242-1e12771647cc)

### To Reproduce

```
name: Verify pull request build
on:
  pull_request:
    branches:
      - '*'
jobs:
  lint:
    name: Run lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'

      - name: Install dependencies
        run: npm ci

      - name: Run eslint on changed files
        uses: tj-actions/eslint-changed-files@v25
        with:
          config_path: .eslintrc.js
          skip_annotations: true
          fail_on_error: false
```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-22.04

### Expected behavior?

To pass the job, even when there are eslint errors

### Relevant log output

```shell
Run tj-actions/eslint-changed-files@v25
  with:
    config_path: .eslintrc.js
    skip_annotations: true
    fail_on_error: false
    token: ***
    all_files: false
    file_extensions: **/*.{ts,tsx,js,jsx}
  
    level: error
    reporter: github-pr-review
    filter_mode: added
    path: .
    skip_initial_fetch: false
    use_rest_api: false
    escape_paths: true
```

### Has all relevant logs been included?

- [X] I've included all relevant logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
The `fail_on_error` input sets the `"# Exit code for review dog when errors are found."` not Eslint which runs when you set ` skip_annotations` to `true`. See: https://github.com/tj-actions/eslint-changed-files/blob/main/entrypoint.sh#L41

To prevent Eslint reported errors from marking the workflow step as failed you would need to use [`continue-on-error`](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error)

```yml
name: Verify pull request build
on:
  pull_request:
    branches:
      - '*'
jobs:
  lint:
    name: Run lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'

      - name: Install dependencies
        run: npm ci

      - name: Run eslint on changed files
        uses: tj-actions/eslint-changed-files@v25
        continue-on-error: true # <-- Add this line
        with:
          config_path: .eslintrc.js
          skip_annotations: true
          fail_on_error: false
```
