### ISSUE TITLE
[BUG] fail_on_error also fails on warnings

### ISSUE THREAD

**Issue by simllll** [tj-actions/eslint-changed-files#589]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

I have an eslint warning (not an error);
![image](https://user-images.githubusercontent.com/5757263/165970640-41a21739-516e-4568-afca-6fdc469680c1.png)

also runnign it locally results into:
![image](https://user-images.githubusercontent.com/5757263/165970474-f9e945b6-bc99-453d-85d0-8f11fbc8fb51.png)

in the pipeline I think this is the relevant output for it:
  {"ruleId":"@typescript-eslint/no-non-null-assertion","severity":1,"message":"Forbidden non-null assertion.","line":43,"column":19,"nodeType":"TSNonNullExpression","messageId":"noNonNull","endLine":43,"endColumn":54}
  reviewdog: input data has violations
Warning: Error running eslint.

```
- name: Run eslint on changed files
        uses: tj-actions/eslint-changed-files@v10.2
        with:
          fail_on_error: true
          config_path: '.eslintrc.js'
          ignore_path: '.eslintignore'
```

fails, even though it's no an error, it's just a warning. It should fail on errors only, or do I miss something here?

### To Reproduce

set fail_on_error: true and use a rule that only produces a warning and not an error.

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04, ubuntu-18.04

### Expected behavior?

It should only fail on errors, not on warnings

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
